CREATE TABLE IF NOT EXISTS USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORIES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE NOT NULL,
    BUDGET_LIMIT REAL DEFAULT 0.0
);

CREATE TABLE IF NOT EXISTS EXPENSES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    AMOUNT REAL NOT NULL,
    DESCRIPTION_ TEXT,
    DATE_ DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)

);

CREATE TABLE IF NOT EXISTS BUDGETS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    AMOUNT REAL NOT NULL,
    MONTH_ TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
)